### PR TITLE
:bug: Escape commit message for json

### LINKED ISSUE #85: Multiline commit message introduces json parse error
## Summary
After passing a multiline commit message future `snow status` invocations fail with the following error message:

```
cwd>snow status
fatal: Unexpected token
 in JSON at position 192
``` 
## Proposed Solution
The received commit message needs to be escaped to be json compliant.

### PR DESCRIPTION
**Pull request by daniellanner**
Fixed an issue where after passing a multiline commit message, future snow status invocations fail.

Fixes #85

### CODE REVIEW

File: src/commit.ts [hunk 1]
```diff
@@ -39,7 +40,7 @@ export class Commit {
     this.tags = [];
     this.userData = {};
     this.repo = repo;
-    this.message = message;
+    this.message = jsonCompliant(message);
```
Comment (seb-mtl) [inline src/commit.ts:43]: Love the function name!

**Review by seb-mtl — APPROVED** [review]
