### PR TITLE
Use strict-equals (Fixes #265)

### LINKED ISSUE #265: Null comparisons without type-checking operators may not work as intended
8 occurrences, see https://deepsource.io/gh/snowtrack/snowfs/issue/JS-0059/occurrences

> Use '===' to compare with null

https://github.com/snowtrack/snowfs/blob/58ac16fe0141421eeba5ea866ad05b6340d92439/src/reference.ts#L60-L70

### PR DESCRIPTION
**Pull request by seb-mtl**
Fixes operator checks

### CODE REVIEW

File: src/commit.ts [hunk 1]
```diff
@@ -85,7 +84,7 @@ export class Commit {
       return;
     }
 
-    if (this.tags == null) {
+    if (this.tags.length === 0) {
       this.tags = [];
```
Comment (daniellanner) [inline src/commit.ts:88]: Creating an empty array if it's length is 0 seems redundant 😄

**Review by daniellanner — APPROVED** [review]

File: src/commit.ts (hunk 1 above)
Comment (seb-mtl) [reply src/commit.ts]: You have a point

😆
